<?php
/**
 * Auto generated by prado-cli.php on 2014-02-25 07:15:04.
 */
class UserRecord extends TActiveRecord
{
	const TABLE='users';

	public $username;
	public $email;
	public $password;
	public $role;
	public $first_name;
	public $last_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	// UserRecord::finder()->findAll()


	$users = UserRecord::finder()->withPosts()->findAll();
    // Tip: The method withXXX() (where XXX is the relationship property name, 
    // in this case, Posts) fetches the corresponding PostRecords using a 
    // second query (not by using a join). The withXXX() method accepts the 
    // same arguments as other finder methods of TActiveRecord, 
    // e.g. withPosts('status = ?', 0).
	public $posts=array(); //holds an array of PostRecord
 
    public static $RELATIONS=array
    (
        'posts' => array(self::HAS_MANY, 'PostRecord'),
    );
}
?>